FROM python:3.10
WORKDIR /adaval/app

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

RUN useradd adaval
USER adaval

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]